"""One user's plan for one calendar week: 3-5 items generated by the
`weekly_plan.generate` job (see app.growth.weekly_plan), each item shaped
`{title, why_now, tool_id, estimated_minutes, expected_impact, category,
completed}`. `reflection` starts empty and is filled in on the following
Monday, when the next week's plan is generated -- it never gets its own
row, so a week's plan and its own retrospective always travel together.
"""

from __future__ import annotations

import uuid
from datetime import date, datetime
from typing import Any

from sqlalchemy import Date, Enum, ForeignKey, Index, Integer, String
from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy.types import JSON

from app.db_types import UTCDateTime, UUIDBinary
from app.models.base import Base, PrimaryKeyMixin, TimestampMixin

WeeklyPlanStatus = Enum("active", "reflected", name="weekly_plan_status")


class WeeklyPlan(PrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "weekly_plans"
    __table_args__ = (
        # One plan per user per week -- created by 0012_growth_plans_and_
        # goals.py; this is also exactly the index the previous-week
        # reflection lookup (app/growth/weekly_plan.py) needs, so no
        # separate index was added for it in Phase 10's index review.
        Index("ux_weekly_plans_user_week", "user_id", "week_start", unique=True),
        {"mysql_engine": "InnoDB", "mysql_charset": "utf8mb4"},
    )

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUIDBinary, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    week_start: Mapped[date] = mapped_column(Date, nullable=False)
    generated_at: Mapped[datetime] = mapped_column(UTCDateTime(), nullable=False)
    focus: Mapped[str] = mapped_column(String(255), nullable=False, default="")
    items: Mapped[list[dict[str, Any]]] = mapped_column(JSON, nullable=False)
    status: Mapped[str] = mapped_column(WeeklyPlanStatus, nullable=False, default="active")
    completed_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    reflection: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)
